/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LaserFrame.java
 *
 * Created on 11.10.2009, 14:13:38
 */

package lasertd2;

import java.awt.Dimension;

/**
 *
 * @author Xels
 */
public class LaserFrame extends javax.swing.JFrame {

  private static final long serialVersionUID = 1L;
  /** Creates new form LaserFrame */
    public LaserFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      laserPanel1 = new lasertd2.LaserPanel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setResizable(false);

      laserPanel1.setBackground(new java.awt.Color(255, 255, 255));
      laserPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

      javax.swing.GroupLayout laserPanel1Layout = new javax.swing.GroupLayout(laserPanel1);
      laserPanel1.setLayout(laserPanel1Layout);
      laserPanel1Layout.setHorizontalGroup(
         laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 682, Short.MAX_VALUE)
      );
      laserPanel1Layout.setVerticalGroup(
         laserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 399, Short.MAX_VALUE)
      );

      jMenu1.setText("File");
      jMenuBar1.add(jMenu1);

      jMenu2.setText("Edit");
      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(laserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(laserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
      public void run() {
                new LaserFrame().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private lasertd2.LaserPanel laserPanel1;
   // End of variables declaration//GEN-END:variables


  @Override
   public Dimension preferredSize() {
      Dimension d = new Dimension(1300,800);
      return d;
   }


}
